"""Generate pilot/src/edh/pilot/CountingController.java from Forge's PlayerControllerAi.

Every decision method is overridden to count the call and delegate to Forge, so a
game's tally shows how many decisions of each kind Forge made for our seat, and
PilotController's own overrides show which of those reach the pilot. Re-run after
a Forge update:  python3 pilot/tools/gen_counting.py
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from edhkit.forge import find_jar  # noqa: E402

DECISION = re.compile(r"^(choose|confirm|declare|order|pay|announce|arrange|assign|divide|specify|vote|mulligan|"
                      r"play|willPutCardOnTop|tuck|exert|enlist|applyManaToCost|helpPay|getAbilityToPlay)")
SKIP = {"chooseCardsYouWonToAddToDeck", "playSounds"}


def split_top(s: str) -> list[str]:
    out, depth, cur = [], 0, ""
    for ch in s:
        if ch == "<":
            depth += 1
        elif ch == ">":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def methods() -> list[tuple[str, str, str, list[str]]]:
    txt = subprocess.run(["javap", "-cp", str(find_jar()), "forge.ai.PlayerControllerAi"],
                         capture_output=True, text=True).stdout
    out = []
    for line in txt.splitlines():
        line = line.strip().rstrip(";")
        if not line.startswith("public ") or " static " in line or " final " in line or "(" not in line:
            continue
        head, params = line[:line.index("(")], line[line.index("(") + 1:line.rindex(")")]
        head = head[len("public "):]
        tparams = ""
        if head.startswith("<"):
            depth = 0
            for i, ch in enumerate(head):
                depth += ch == "<"
                depth -= ch == ">"
                if depth == 0:
                    tparams, head = head[:i + 1], head[i + 1:].strip()
                    break
        if " " not in head:  # constructor
            continue
        ret, name = head.rsplit(" ", 1)
        if not DECISION.match(name) or name in SKIP:
            continue
        out.append((tparams, ret.replace("$", "."), name, [p.replace("$", ".") for p in split_top(params)]))
    # javap also lists compiler bridge methods (same parameters, a supertype return such as
    # CardCollectionView for CardCollection); keep the specific one
    seen: dict[tuple, tuple] = {}
    for m in out:
        key = (m[2], tuple(m[3]))
        if key not in seen or seen[key][1].endswith("View"):
            seen[key] = m
    return list(seen.values())


IMPLICIT = '''
    /** Decisions Forge's AI makes inside a play, outside any controller method. */
    private void countImplicit(SpellAbility sa) {
        try {
            if (sa == null || sa.isLandAbility()) return;
            if (sa.getPayCosts() != null && sa.getPayCosts().hasManaCost()) count("(implicit) mana payment");
            if (sa.getPayCosts() != null && sa.getPayCosts().getTotalMana() != null
                    && sa.getPayCosts().getTotalMana().countX() > 0) count("(implicit) X value");
            if (sa.getApi() == forge.game.ability.ApiType.Charm) count("(implicit) modal choice");
            if (sa.usesTargeting() && sa.getMaxTargets() > 1) count("(implicit) multi-target");
        } catch (Exception ignored) { }
    }
'''


def main() -> None:
    body = []
    for tp, ret, name, params in methods():
        args = [f"a{i}" for i in range(len(params))]
        decl = ", ".join(f"{t} {a}" for t, a in zip(params, args))
        call = f"super.{name}({', '.join(args)})"
        extra = ""
        if name == "playChosenSpellAbility":
            extra = " countImplicit(a0);"
        if name == "orderSimultaneousSa":
            extra = ' if (a0 != null && a0.size() > 1) count("(implicit) order of our simultaneous triggers");'
        stmt = f"{call};" if ret == "void" else f"return {call};"
        body.append(f"    @Override\n    public {tp + ' ' if tp else ''}{ret} {name}({decl}) {{\n"
                    f"        count(\"{name}\");{extra}\n        {stmt}\n    }}\n")
    src = f'''package edh.pilot;

import java.util.Map;
import java.util.TreeMap;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

import forge.LobbyPlayer;
import forge.ai.PlayerControllerAi;
import forge.game.Game;
import forge.game.player.Player;
import forge.game.spellability.SpellAbility;

/**
 * GENERATED by pilot/tools/gen_counting.py: do not edit by hand.
 * Counts every decision Forge's AI controller makes for our seat, then delegates.
 */
public class CountingController extends PlayerControllerAi {{
    private static final Map<String, AtomicInteger> CALLS = new ConcurrentHashMap<>();

    public CountingController(Game game, Player p, LobbyPlayer lp) {{
        super(game, p, lp);
    }}

    static void count(String what) {{
        CALLS.computeIfAbsent(what, k -> new AtomicInteger()).incrementAndGet();
    }}

    /** JSON of this game's counts, then reset. */
    static String drain() {{
        StringBuilder b = new StringBuilder("{{");
        for (Map.Entry<String, AtomicInteger> e : new TreeMap<>(CALLS).entrySet()) {{
            if (b.length() > 1) b.append(',');
            b.append('"').append(e.getKey()).append("\\":").append(e.getValue().get());
        }}
        CALLS.clear();
        return b.append('}}').toString();
    }}
{IMPLICIT}
{chr(10).join(body)}}}
'''
    (ROOT / "pilot/src/edh/pilot/CountingController.java").write_text(src)
    print(f"{len(body)} decision methods")


if __name__ == "__main__":
    main()
