package edh.pilot;

import java.util.Map;
import java.util.TreeMap;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

import forge.LobbyPlayer;
import forge.ai.PlayerControllerAi;
import forge.game.Game;
import forge.game.player.Player;
import forge.game.spellability.SpellAbility;

/**
 * GENERATED by pilot/tools/gen_counting.py: do not edit by hand.
 * Counts every decision Forge's AI controller makes for our seat, then delegates.
 */
public class CountingController extends PlayerControllerAi {
    private static final Map<String, AtomicInteger> CALLS = new ConcurrentHashMap<>();

    public CountingController(Game game, Player p, LobbyPlayer lp) {
        super(game, p, lp);
    }

    static void count(String what) {
        CALLS.computeIfAbsent(what, k -> new AtomicInteger()).incrementAndGet();
    }

    /** JSON of this game's counts, then reset. */
    static String drain() {
        StringBuilder b = new StringBuilder("{");
        for (Map.Entry<String, AtomicInteger> e : new TreeMap<>(CALLS).entrySet()) {
            if (b.length() > 1) b.append(',');
            b.append('"').append(e.getKey()).append("\":").append(e.getValue().get());
        }
        CALLS.clear();
        return b.append('}').toString();
    }

    /** Decisions Forge's AI makes inside a play, outside any controller method. */
    private void countImplicit(SpellAbility sa) {
        try {
            if (sa == null || sa.isLandAbility()) return;
            if (sa.getPayCosts() != null && sa.getPayCosts().hasManaCost()) count("(implicit) mana payment");
            if (sa.getPayCosts() != null && sa.getPayCosts().getTotalMana() != null
                    && sa.getPayCosts().getTotalMana().countX() > 0) count("(implicit) X value");
            if (sa.getApi() == forge.game.ability.ApiType.Charm) count("(implicit) modal choice");
            if (sa.usesTargeting() && sa.getMaxTargets() > 1) count("(implicit) multi-target");
        } catch (Exception ignored) { }
    }

    @Override
    public forge.game.spellability.SpellAbility getAbilityToPlay(forge.game.card.Card a0, java.util.List<forge.game.spellability.SpellAbility> a1, forge.util.ITriggerEvent a2) {
        count("getAbilityToPlay");
        return super.getAbilityToPlay(a0, a1, a2);
    }

    @Override
    public java.util.Map<forge.game.card.Card, java.lang.Integer> assignCombatDamage(forge.game.card.Card a0, forge.game.card.CardCollectionView a1, forge.game.card.CardCollectionView a2, int a3, forge.game.GameEntity a4, boolean a5) {
        count("assignCombatDamage");
        return super.assignCombatDamage(a0, a1, a2, a3, a4, a5);
    }

    @Override
    public java.util.Map<forge.game.GameEntity, java.lang.Integer> divideShield(forge.game.card.Card a0, java.util.Map<forge.game.GameEntity, java.lang.Integer> a1, int a2) {
        count("divideShield");
        return super.divideShield(a0, a1, a2);
    }

    @Override
    public java.util.Map<java.lang.Byte, java.lang.Integer> specifyManaCombo(forge.game.spellability.SpellAbility a0, forge.card.ColorSet a1, int a2, boolean a3) {
        count("specifyManaCombo");
        return super.specifyManaCombo(a0, a1, a2, a3);
    }

    @Override
    public java.lang.Integer announceRequirements(forge.game.spellability.SpellAbility a0, int a1, int a2, java.lang.String a3) {
        count("announceRequirements");
        return super.announceRequirements(a0, a1, a2, a3);
    }

    @Override
    public forge.game.card.CardCollectionView choosePermanentsToSacrifice(forge.game.spellability.SpellAbility a0, int a1, int a2, forge.game.card.CardCollectionView a3, java.lang.String a4) {
        count("choosePermanentsToSacrifice");
        return super.choosePermanentsToSacrifice(a0, a1, a2, a3, a4);
    }

    @Override
    public forge.game.card.CardCollectionView choosePermanentsToDestroy(forge.game.spellability.SpellAbility a0, int a1, int a2, forge.game.card.CardCollectionView a3, java.lang.String a4) {
        count("choosePermanentsToDestroy");
        return super.choosePermanentsToDestroy(a0, a1, a2, a3, a4);
    }

    @Override
    public forge.game.card.CardCollectionView chooseCardsForEffect(forge.game.card.CardCollectionView a0, forge.game.spellability.SpellAbility a1, java.lang.String a2, int a3, int a4, boolean a5, java.util.Map<java.lang.String, java.lang.Object> a6) {
        count("chooseCardsForEffect");
        return super.chooseCardsForEffect(a0, a1, a2, a3, a4, a5, a6);
    }

    @Override
    public java.util.List<forge.game.card.Card> chooseContraptionsToCrank(java.util.List<forge.game.card.Card> a0) {
        count("chooseContraptionsToCrank");
        return super.chooseContraptionsToCrank(a0);
    }

    @Override
    public boolean helpPayForAssistSpell(forge.game.mana.ManaCostBeingPaid a0, forge.game.spellability.SpellAbility a1, int a2, int a3) {
        count("helpPayForAssistSpell");
        return super.helpPayForAssistSpell(a0, a1, a2, a3);
    }

    @Override
    public forge.game.player.Player choosePlayerToAssistPayment(forge.util.collect.FCollectionView<forge.game.player.Player> a0, forge.game.spellability.SpellAbility a1, java.lang.String a2, int a3) {
        count("choosePlayerToAssistPayment");
        return super.choosePlayerToAssistPayment(a0, a1, a2, a3);
    }

    @Override
    public <T extends forge.game.GameEntity> T chooseSingleEntityForEffect(forge.util.collect.FCollectionView<T> a0, forge.game.player.DelayedReveal a1, forge.game.spellability.SpellAbility a2, java.lang.String a3, boolean a4, forge.game.player.Player a5, java.util.Map<java.lang.String, java.lang.Object> a6) {
        count("chooseSingleEntityForEffect");
        return super.chooseSingleEntityForEffect(a0, a1, a2, a3, a4, a5, a6);
    }

    @Override
    public <T extends forge.game.GameEntity> java.util.List<T> chooseEntitiesForEffect(forge.util.collect.FCollectionView<T> a0, int a1, int a2, forge.game.player.DelayedReveal a3, forge.game.spellability.SpellAbility a4, java.lang.String a5, forge.game.player.Player a6, java.util.Map<java.lang.String, java.lang.Object> a7) {
        count("chooseEntitiesForEffect");
        return super.chooseEntitiesForEffect(a0, a1, a2, a3, a4, a5, a6, a7);
    }

    @Override
    public java.util.List<forge.game.spellability.SpellAbility> chooseSpellAbilitiesForEffect(java.util.List<forge.game.spellability.SpellAbility> a0, forge.game.spellability.SpellAbility a1, java.lang.String a2, int a3, java.util.Map<java.lang.String, java.lang.Object> a4) {
        count("chooseSpellAbilitiesForEffect");
        return super.chooseSpellAbilitiesForEffect(a0, a1, a2, a3, a4);
    }

    @Override
    public forge.game.spellability.SpellAbility chooseSingleSpellForEffect(java.util.List<forge.game.spellability.SpellAbility> a0, forge.game.spellability.SpellAbility a1, java.lang.String a2, java.util.Map<java.lang.String, java.lang.Object> a3) {
        count("chooseSingleSpellForEffect");
        return super.chooseSingleSpellForEffect(a0, a1, a2, a3);
    }

    @Override
    public boolean confirmAction(forge.game.spellability.SpellAbility a0, forge.game.player.PlayerActionConfirmMode a1, java.lang.String a2, java.util.List<java.lang.String> a3, forge.game.card.Card a4, java.util.Map<java.lang.String, java.lang.Object> a5) {
        count("confirmAction");
        return super.confirmAction(a0, a1, a2, a3, a4, a5);
    }

    @Override
    public boolean confirmBidAction(forge.game.spellability.SpellAbility a0, forge.game.player.PlayerActionConfirmMode a1, java.lang.String a2, int a3, forge.game.player.Player a4) {
        count("confirmBidAction");
        return super.confirmBidAction(a0, a1, a2, a3, a4);
    }

    @Override
    public boolean confirmStaticApplication(forge.game.card.Card a0, forge.game.player.PlayerActionConfirmMode a1, java.lang.String a2, java.lang.String a3) {
        count("confirmStaticApplication");
        return super.confirmStaticApplication(a0, a1, a2, a3);
    }

    @Override
    public boolean confirmTrigger(forge.game.trigger.WrappedAbility a0) {
        count("confirmTrigger");
        return super.confirmTrigger(a0);
    }

    @Override
    public boolean confirmPayment(forge.game.cost.CostPart a0, java.lang.String a1, forge.game.spellability.SpellAbility a2) {
        count("confirmPayment");
        return super.confirmPayment(a0, a1, a2);
    }

    @Override
    public boolean confirmReplacementEffect(forge.game.replacement.ReplacementEffect a0, forge.game.spellability.SpellAbility a1, forge.game.GameEntity a2, java.lang.String a3) {
        count("confirmReplacementEffect");
        return super.confirmReplacementEffect(a0, a1, a2, a3);
    }

    @Override
    public java.util.List<forge.game.card.Card> exertAttackers(java.util.List<forge.game.card.Card> a0) {
        count("exertAttackers");
        return super.exertAttackers(a0);
    }

    @Override
    public java.util.List<forge.game.card.Card> enlistAttackers(java.util.List<forge.game.card.Card> a0) {
        count("enlistAttackers");
        return super.enlistAttackers(a0);
    }

    @Override
    public forge.game.card.CardCollection orderBlockers(forge.game.card.Card a0, forge.game.card.CardCollection a1) {
        count("orderBlockers");
        return super.orderBlockers(a0, a1);
    }

    @Override
    public forge.game.card.CardCollection orderBlocker(forge.game.card.Card a0, forge.game.card.Card a1, forge.game.card.CardCollection a2) {
        count("orderBlocker");
        return super.orderBlocker(a0, a1, a2);
    }

    @Override
    public forge.game.card.CardCollection orderAttackers(forge.game.card.Card a0, forge.game.card.CardCollection a1) {
        count("orderAttackers");
        return super.orderAttackers(a0, a1);
    }

    @Override
    public org.apache.commons.lang3.tuple.ImmutablePair<forge.game.card.CardCollection, forge.game.card.CardCollection> arrangeForScry(forge.game.card.CardCollection a0) {
        count("arrangeForScry");
        return super.arrangeForScry(a0);
    }

    @Override
    public org.apache.commons.lang3.tuple.ImmutablePair<forge.game.card.CardCollection, forge.game.card.CardCollection> arrangeForSurveil(forge.game.card.CardCollection a0) {
        count("arrangeForSurveil");
        return super.arrangeForSurveil(a0);
    }

    @Override
    public boolean willPutCardOnTop(forge.game.card.Card a0) {
        count("willPutCardOnTop");
        return super.willPutCardOnTop(a0);
    }

    @Override
    public forge.game.card.CardCollectionView orderMoveToZoneList(forge.game.card.CardCollectionView a0, forge.game.zone.ZoneType a1, forge.game.spellability.SpellAbility a2) {
        count("orderMoveToZoneList");
        return super.orderMoveToZoneList(a0, a1, a2);
    }

    @Override
    public forge.game.card.CardCollection chooseCardsToDiscardFrom(forge.game.player.Player a0, forge.game.spellability.SpellAbility a1, forge.game.card.CardCollection a2, int a3, int a4, forge.game.card.CardCollectionView a5) {
        count("chooseCardsToDiscardFrom");
        return super.chooseCardsToDiscardFrom(a0, a1, a2, a3, a4, a5);
    }

    @Override
    public void playSpellAbilityNoStack(forge.game.spellability.SpellAbility a0, boolean a1) {
        count("playSpellAbilityNoStack");
        super.playSpellAbilityNoStack(a0, a1);
    }

    @Override
    public forge.game.card.CardCollectionView chooseCardsToDelve(int a0, forge.game.card.CardCollection a1) {
        count("chooseCardsToDelve");
        return super.chooseCardsToDelve(a0, a1);
    }

    @Override
    public forge.game.card.CardCollectionView chooseCardsToDiscardUnlessType(int a0, forge.game.card.CardCollectionView a1, java.lang.String[] a2, forge.game.spellability.SpellAbility a3) {
        count("chooseCardsToDiscardUnlessType");
        return super.chooseCardsToDiscardUnlessType(a0, a1, a2, a3);
    }

    @Override
    public forge.game.mana.Mana chooseManaFromPool(java.util.List<forge.game.mana.Mana> a0) {
        count("chooseManaFromPool");
        return super.chooseManaFromPool(a0);
    }

    @Override
    public java.lang.String chooseSomeType(java.lang.String a0, forge.game.spellability.SpellAbility a1, java.util.Collection<java.lang.String> a2, boolean a3) {
        count("chooseSomeType");
        return super.chooseSomeType(a0, a1, a2, a3);
    }

    @Override
    public java.lang.Object vote(forge.game.spellability.SpellAbility a0, java.lang.String a1, java.util.List<java.lang.Object> a2, com.google.common.collect.ListMultimap<java.lang.Object, forge.game.player.Player> a3, forge.game.player.Player a4, boolean a5) {
        count("vote");
        return super.vote(a0, a1, a2, a3, a4, a5);
    }

    @Override
    public java.lang.String chooseSector(forge.game.card.Card a0, java.lang.String a1, java.util.List<java.lang.String> a2) {
        count("chooseSector");
        return super.chooseSector(a0, a1, a2);
    }

    @Override
    public int chooseSprocket(forge.game.card.Card a0, java.util.List<java.lang.Integer> a1) {
        count("chooseSprocket");
        return super.chooseSprocket(a0, a1);
    }

    @Override
    public forge.game.PlanarDice choosePDRollToIgnore(java.util.List<forge.game.PlanarDice> a0) {
        count("choosePDRollToIgnore");
        return super.choosePDRollToIgnore(a0);
    }

    @Override
    public java.lang.Integer chooseRollToIgnore(java.util.List<java.lang.Integer> a0) {
        count("chooseRollToIgnore");
        return super.chooseRollToIgnore(a0);
    }

    @Override
    public java.util.List<java.lang.Integer> chooseDiceToReroll(java.util.List<java.lang.Integer> a0) {
        count("chooseDiceToReroll");
        return super.chooseDiceToReroll(a0);
    }

    @Override
    public java.lang.Integer chooseRollToModify(java.util.List<java.lang.Integer> a0) {
        count("chooseRollToModify");
        return super.chooseRollToModify(a0);
    }

    @Override
    public forge.game.ability.effects.RollDiceEffect.DieRollResult chooseRollToSwap(java.util.List<forge.game.ability.effects.RollDiceEffect.DieRollResult> a0) {
        count("chooseRollToSwap");
        return super.chooseRollToSwap(a0);
    }

    @Override
    public java.lang.String chooseRollSwapValue(java.util.List<java.lang.String> a0, java.lang.Integer a1, int a2, int a3) {
        count("chooseRollSwapValue");
        return super.chooseRollSwapValue(a0, a1, a2, a3);
    }

    @Override
    public boolean mulliganKeepHand(forge.game.player.Player a0, int a1) {
        count("mulliganKeepHand");
        return super.mulliganKeepHand(a0, a1);
    }

    @Override
    public forge.game.card.CardCollectionView tuckCardsViaMulligan(forge.game.card.CardCollectionView a0, int a1) {
        count("tuckCardsViaMulligan");
        return super.tuckCardsViaMulligan(a0, a1);
    }

    @Override
    public void declareAttackers(forge.game.player.Player a0, forge.game.combat.Combat a1) {
        count("declareAttackers");
        super.declareAttackers(a0, a1);
    }

    @Override
    public void declareBlockers(forge.game.player.Player a0, forge.game.combat.Combat a1) {
        count("declareBlockers");
        super.declareBlockers(a0, a1);
    }

    @Override
    public java.util.List<forge.game.spellability.SpellAbility> chooseSpellAbilityToPlay() {
        count("chooseSpellAbilityToPlay");
        return super.chooseSpellAbilityToPlay();
    }

    @Override
    public boolean playChosenSpellAbility(forge.game.spellability.SpellAbility a0) {
        count("playChosenSpellAbility"); countImplicit(a0);
        return super.playChosenSpellAbility(a0);
    }

    @Override
    public forge.game.card.CardCollectionView chooseCardsToDiscardToMaximumHandSize(int a0) {
        count("chooseCardsToDiscardToMaximumHandSize");
        return super.chooseCardsToDiscardToMaximumHandSize(a0);
    }

    @Override
    public forge.game.card.CardCollectionView chooseCardsToRevealFromHand(int a0, int a1, forge.game.card.CardCollectionView a2) {
        count("chooseCardsToRevealFromHand");
        return super.chooseCardsToRevealFromHand(a0, a1, a2);
    }

    @Override
    public forge.game.player.Player chooseStartingPlayer(boolean a0) {
        count("chooseStartingPlayer");
        return super.chooseStartingPlayer(a0);
    }

    @Override
    public forge.game.zone.PlayerZone chooseStartingHand(java.util.List<forge.game.zone.PlayerZone> a0) {
        count("chooseStartingHand");
        return super.chooseStartingHand(a0);
    }

    @Override
    public java.util.List<forge.game.spellability.SpellAbility> chooseSaToActivateFromOpeningHand(java.util.List<forge.game.spellability.SpellAbility> a0) {
        count("chooseSaToActivateFromOpeningHand");
        return super.chooseSaToActivateFromOpeningHand(a0);
    }

    @Override
    public int chooseNumber(forge.game.spellability.SpellAbility a0, java.lang.String a1, int a2, int a3) {
        count("chooseNumber");
        return super.chooseNumber(a0, a1, a2, a3);
    }

    @Override
    public int chooseNumber(forge.game.spellability.SpellAbility a0, java.lang.String a1, int a2, int a3, java.util.Map<java.lang.String, java.lang.Object> a4) {
        count("chooseNumber");
        return super.chooseNumber(a0, a1, a2, a3, a4);
    }

    @Override
    public int chooseNumber(forge.game.spellability.SpellAbility a0, java.lang.String a1, java.util.List<java.lang.Integer> a2, forge.game.player.Player a3) {
        count("chooseNumber");
        return super.chooseNumber(a0, a1, a2, a3);
    }

    @Override
    public boolean chooseFlipResult(forge.game.spellability.SpellAbility a0, forge.game.player.Player a1, boolean a2) {
        count("chooseFlipResult");
        return super.chooseFlipResult(a0, a1, a2);
    }

    @Override
    public org.apache.commons.lang3.tuple.Pair<forge.game.spellability.SpellAbilityStackInstance, forge.game.GameObject> chooseTarget(forge.game.spellability.SpellAbility a0, java.util.List<org.apache.commons.lang3.tuple.Pair<forge.game.spellability.SpellAbilityStackInstance, forge.game.GameObject>> a1) {
        count("chooseTarget");
        return super.chooseTarget(a0, a1);
    }

    @Override
    public boolean chooseBinary(forge.game.spellability.SpellAbility a0, java.lang.String a1, forge.game.player.PlayerController.BinaryChoiceType a2, java.lang.Boolean a3) {
        count("chooseBinary");
        return super.chooseBinary(a0, a1, a2, a3);
    }

    @Override
    public boolean chooseBinary(forge.game.spellability.SpellAbility a0, java.lang.String a1, forge.game.player.PlayerController.BinaryChoiceType a2, java.util.Map<java.lang.String, java.lang.Object> a3) {
        count("chooseBinary");
        return super.chooseBinary(a0, a1, a2, a3);
    }

    @Override
    public java.util.List<forge.game.spellability.AbilitySub> chooseModeForAbility(forge.game.spellability.SpellAbility a0, java.util.List<forge.game.spellability.AbilitySub> a1, int a2, int a3, boolean a4) {
        count("chooseModeForAbility");
        return super.chooseModeForAbility(a0, a1, a2, a3, a4);
    }

    @Override
    public byte chooseColorAllowColorless(java.lang.String a0, forge.game.card.Card a1, forge.card.ColorSet a2) {
        count("chooseColorAllowColorless");
        return super.chooseColorAllowColorless(a0, a1, a2);
    }

    @Override
    public byte chooseColor(java.lang.String a0, forge.game.spellability.SpellAbility a1, forge.card.ColorSet a2) {
        count("chooseColor");
        return super.chooseColor(a0, a1, a2);
    }

    @Override
    public forge.card.ColorSet chooseColors(java.lang.String a0, forge.game.spellability.SpellAbility a1, int a2, int a3, forge.card.ColorSet a4) {
        count("chooseColors");
        return super.chooseColors(a0, a1, a2, a3, a4);
    }

    @Override
    public forge.game.card.CounterType chooseCounterType(java.util.List<forge.game.card.CounterType> a0, forge.game.spellability.SpellAbility a1, java.lang.String a2, java.util.Map<java.lang.String, java.lang.Object> a3) {
        count("chooseCounterType");
        return super.chooseCounterType(a0, a1, a2, a3);
    }

    @Override
    public java.lang.String chooseKeywordForPump(java.util.List<java.lang.String> a0, forge.game.spellability.SpellAbility a1, java.lang.String a2, forge.game.card.Card a3) {
        count("chooseKeywordForPump");
        return super.chooseKeywordForPump(a0, a1, a2, a3);
    }

    @Override
    public forge.game.replacement.ReplacementEffect chooseSingleReplacementEffect(java.util.List<forge.game.replacement.ReplacementEffect> a0) {
        count("chooseSingleReplacementEffect");
        return super.chooseSingleReplacementEffect(a0);
    }

    @Override
    public forge.game.staticability.StaticAbility chooseSingleStaticAbility(java.util.List<forge.game.staticability.StaticAbility> a0) {
        count("chooseSingleStaticAbility");
        return super.chooseSingleStaticAbility(a0);
    }

    @Override
    public java.lang.String chooseProtectionType(forge.game.spellability.SpellAbility a0, java.util.List<java.lang.String> a1) {
        count("chooseProtectionType");
        return super.chooseProtectionType(a0, a1);
    }

    @Override
    public boolean payManaCost(forge.card.mana.ManaCost a0, forge.game.cost.CostPartMana a1, forge.game.spellability.SpellAbility a2, java.lang.String a3, forge.game.mana.ManaConversionMatrix a4, boolean a5) {
        count("payManaCost");
        return super.payManaCost(a0, a1, a2, a3, a4, a5);
    }

    @Override
    public boolean payCombatCost(forge.game.card.Card a0, forge.game.cost.Cost a1, forge.game.spellability.SpellAbility a2, java.lang.String a3) {
        count("payCombatCost");
        return super.payCombatCost(a0, a1, a2, a3);
    }

    @Override
    public forge.game.card.CardCollectionView chooseCardsForCost(forge.game.card.CardCollectionView a0, forge.game.spellability.SpellAbility a1, forge.game.cost.CostPartWithList a2, int a3, boolean a4, java.lang.String a5) {
        count("chooseCardsForCost");
        return super.chooseCardsForCost(a0, a1, a2, a3, a4, a5);
    }

    @Override
    public boolean applyManaToCost(forge.game.mana.ManaCostBeingPaid a0, forge.game.spellability.SpellAbility a1, java.lang.String a2, forge.game.mana.ManaConversionMatrix a3, boolean a4) {
        count("applyManaToCost");
        return super.applyManaToCost(a0, a1, a2, a3, a4);
    }

    @Override
    public boolean payCostToPreventEffect(forge.game.cost.Cost a0, forge.game.spellability.SpellAbility a1, boolean a2, forge.util.collect.FCollectionView<forge.game.player.Player> a3) {
        count("payCostToPreventEffect");
        return super.payCostToPreventEffect(a0, a1, a2, a3);
    }

    @Override
    public boolean payCostDuringRoll(forge.game.cost.Cost a0, forge.game.spellability.SpellAbility a1) {
        count("payCostDuringRoll");
        return super.payCostDuringRoll(a0, a1);
    }

    @Override
    public java.util.List<forge.game.spellability.SpellAbility> orderSimultaneousSa(java.util.List<forge.game.spellability.SpellAbility> a0) {
        count("orderSimultaneousSa"); if (a0 != null && a0.size() > 1) count("(implicit) order of our simultaneous triggers");
        return super.orderSimultaneousSa(a0);
    }

    @Override
    public void orderAndPlaySimultaneousSa(java.util.List<forge.game.spellability.SpellAbility> a0) {
        count("orderAndPlaySimultaneousSa");
        super.orderAndPlaySimultaneousSa(a0);
    }

    @Override
    public boolean playTrigger(forge.game.card.Card a0, forge.game.trigger.WrappedAbility a1, boolean a2) {
        count("playTrigger");
        return super.playTrigger(a0, a1, a2);
    }

    @Override
    public boolean playSaFromPlayEffect(forge.game.spellability.SpellAbility a0) {
        count("playSaFromPlayEffect");
        return super.playSaFromPlayEffect(a0);
    }

    @Override
    public boolean chooseTargetsFor(forge.game.spellability.SpellAbility a0) {
        count("chooseTargetsFor");
        return super.chooseTargetsFor(a0);
    }

    @Override
    public forge.game.spellability.TargetChoices chooseNewTargetsFor(forge.game.spellability.SpellAbility a0, java.util.function.Predicate<forge.game.GameObject> a1, boolean a2) {
        count("chooseNewTargetsFor");
        return super.chooseNewTargetsFor(a0, a1, a2);
    }

    @Override
    public boolean chooseCardsPile(forge.game.spellability.SpellAbility a0, forge.game.card.CardCollectionView a1, forge.game.card.CardCollectionView a2, java.lang.String a3) {
        count("chooseCardsPile");
        return super.chooseCardsPile(a0, a1, a2, a3);
    }

    @Override
    public java.util.Map<forge.game.card.Card, forge.card.mana.ManaCostShard> chooseCardsForConvokeOrImprovise(forge.game.spellability.SpellAbility a0, forge.card.mana.ManaCost a1, forge.game.card.CardCollectionView a2, boolean a3, boolean a4, java.lang.Integer a5) {
        count("chooseCardsForConvokeOrImprovise");
        return super.chooseCardsForConvokeOrImprovise(a0, a1, a2, a3, a4, a5);
    }

    @Override
    public java.lang.String chooseCardName(forge.game.spellability.SpellAbility a0, java.util.List<forge.card.ICardFace> a1, java.lang.String a2) {
        count("chooseCardName");
        return super.chooseCardName(a0, a1, a2);
    }

    @Override
    public java.lang.String chooseCardName(forge.game.spellability.SpellAbility a0, java.util.function.Predicate<forge.card.ICardFace> a1, java.lang.String a2, java.lang.String a3) {
        count("chooseCardName");
        return super.chooseCardName(a0, a1, a2, a3);
    }

    @Override
    public forge.game.card.Card chooseSingleCardForZoneChange(forge.game.zone.ZoneType a0, java.util.List<forge.game.zone.ZoneType> a1, forge.game.spellability.SpellAbility a2, forge.game.card.CardCollection a3, forge.game.player.DelayedReveal a4, java.lang.String a5, boolean a6, forge.game.player.Player a7) {
        count("chooseSingleCardForZoneChange");
        return super.chooseSingleCardForZoneChange(a0, a1, a2, a3, a4, a5, a6, a7);
    }

    @Override
    public java.util.List<forge.game.card.Card> chooseCardsForZoneChange(forge.game.zone.ZoneType a0, java.util.List<forge.game.zone.ZoneType> a1, forge.game.spellability.SpellAbility a2, forge.game.card.CardCollection a3, int a4, int a5, forge.game.player.DelayedReveal a6, java.lang.String a7, forge.game.player.Player a8) {
        count("chooseCardsForZoneChange");
        return super.chooseCardsForZoneChange(a0, a1, a2, a3, a4, a5, a6, a7, a8);
    }

    @Override
    public forge.card.ICardFace chooseSingleCardFace(forge.game.spellability.SpellAbility a0, java.util.List<forge.card.ICardFace> a1, java.lang.String a2) {
        count("chooseSingleCardFace");
        return super.chooseSingleCardFace(a0, a1, a2);
    }

    @Override
    public forge.card.ICardFace chooseSingleCardFace(forge.game.spellability.SpellAbility a0, java.lang.String a1, java.util.function.Predicate<forge.card.ICardFace> a2, java.lang.String a3) {
        count("chooseSingleCardFace");
        return super.chooseSingleCardFace(a0, a1, a2, a3);
    }

    @Override
    public forge.game.card.CardState chooseSingleCardState(forge.game.spellability.SpellAbility a0, java.util.List<forge.game.card.CardState> a1, java.lang.String a2, java.util.Map<java.lang.String, java.lang.Object> a3) {
        count("chooseSingleCardState");
        return super.chooseSingleCardState(a0, a1, a2, a3);
    }

    @Override
    public java.util.List<forge.game.card.Card> chooseCardsForSplice(forge.game.spellability.SpellAbility a0, java.util.List<forge.game.card.Card> a1) {
        count("chooseCardsForSplice");
        return super.chooseCardsForSplice(a0, a1);
    }

    @Override
    public java.util.List<forge.game.spellability.OptionalCostValue> chooseOptionalCosts(forge.game.spellability.SpellAbility a0, java.util.List<forge.game.spellability.OptionalCostValue> a1) {
        count("chooseOptionalCosts");
        return super.chooseOptionalCosts(a0, a1);
    }

    @Override
    public int chooseNumberForKeywordCost(forge.game.spellability.SpellAbility a0, forge.game.cost.Cost a1, forge.game.keyword.KeywordInterface a2, java.lang.String a3, int a4) {
        count("chooseNumberForKeywordCost");
        return super.chooseNumberForKeywordCost(a0, a1, a2, a3, a4);
    }

    @Override
    public int chooseNumberForCostReduction(forge.game.spellability.SpellAbility a0, int a1, int a2) {
        count("chooseNumberForCostReduction");
        return super.chooseNumberForCostReduction(a0, a1, a2);
    }

    @Override
    public java.util.List<forge.game.cost.CostPart> orderCosts(java.util.List<forge.game.cost.CostPart> a0) {
        count("orderCosts");
        return super.orderCosts(a0);
    }

    @Override
    public forge.game.card.CardCollection chooseCardsForEffectMultiple(java.util.Map<java.lang.String, forge.game.card.CardCollection> a0, forge.game.spellability.SpellAbility a1, java.lang.String a2, boolean a3) {
        count("chooseCardsForEffectMultiple");
        return super.chooseCardsForEffectMultiple(a0, a1, a2, a3);
    }
}
